# Basic config
is_training: 1
model_id: "test"
model: "ParallelTime"
fix_seed: 2023

# Data loader
data: "custom"
root_path: "./data/electricity/"
data_path: "electricity.csv"
features: "M"
target: "OT"
freq: "h"
checkpoints: "./checkpoints/"

# Forecasting task
seq_len: 512
label_len: 48
pred_len: 96

# Model definition
nvars_val: 999999999      # by defualt using inf number of varibles
nvars_training: 999999999 # by defualt using inf number of varibles
factor: 1
dropout: 0.1
att_dropout: 0.1
embed: "timeF"
activation: "gelu"
output_attention: false
do_predict: false

# Optimization
num_workers: 10
itr: 1
train_epochs: 1
batch_size: 128
patience: 3
learning_rate: 0.0001
pct_start: 0.3
loss: "huber"
huber_delta: 1.0
lradj: "OneCycleLR"
inverse: false

# GPU
use_gpu: true
gpu: 0
use_multi_gpu: false
devices: "0,1,2,3"

# ParallelTime
dim: 16
head_size: 4
n_block_layers: 2
ffn_multiplier: 3.0
patch_len: 16
stride: 16
patches_window_len: 4
num_register_tokens: 32
expend_ratio_scaler: 16
proj_expend_ratio: 16
proj_squeeze_ratio: 2
dropout_proj: 0.05

# Mamba
comment: ""
d_state: 16
d_conv: 2