defaults:
  - default

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/ETTm1/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/ETTm1/${now:%H-%M-%S}

# Data loader
model_id: ETTm1
data: "ETTm1"
root_path: "./dataset/ETT-small/"
data_path: "ETTm1.csv"

# Forecasting task
seq_len: 512
pred_len: 96

# Model definition
num_total_nvars: 7

# Optimization
train_epochs: 30
learning_rate: 0.0001
batch_size: 64
patience: 10

# Total architucture
patch_len: 16
dim: 32
ffn_multiplier: 3.0
proj_expend_ratio: 8
proj_squeeze_ratio: 1 
dropout: 0.25