defaults:
  - default

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/ili/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/ili/${now:%H-%M-%S}

# Data loader
model_id: ili
data: "custom"
root_path: "./dataset/illness/"
data_path: "national_illness.csv"

# Forecasting task
seq_len: 128
pred_len: 24

# Model definition
num_total_nvars: 7

# Optimization
train_epochs: 10
learning_rate: 0.012
batch_size: 64
patience: 7

# Total architucture
patch_len: 16
dim: 32
ffn_multiplier: 4.0
proj_expend_ratio: 6
proj_squeeze_ratio: 2
dropout: 0.3